sudo: false
language: python
python:
    3.6
dist: xenial

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - |
    echo "name: test-env" > requirements.yml
    echo "dependencies:" >> requirements.yml
    echo "  - cnv_facets" >> requirements.yml
    echo "  - libgfortran" >> requirements.yml
  #   awk -v run=0 '{
  #      if($0 ~ "run:"){
  #          run=1
  #          print "dependencies:"
  #      }
  #      else if(run == 1 && $0 ~ "-"){
  #          print $0
  #      }
  #      else if(run == 1 && $0 !~ "-"){
  #          exit
  #      }
  #   }' bioconda_recipe/meta.yaml >> requirements.yml
  - conda env create -f requirements.yml
  - source activate test-env
  
script:
    - cnv_facets.R -h
#    - bunzip2 -c test_data/ref/hg38.chroms.fa.bz2 > test_data/ref/hg38.chroms.fa
#    - cd test/medusa01 && python3 test.py
#    - cd ../manifest && python3 test.py
#    - cd ../utils && python3 test.py

