# To be transfered to https://github.com/bioconda/bioconda-recipes
{% set version = "0.1.0" %}
{% set sha256 = "xyz" %}

package:
  name: medusa
  version: '{{version}}'

source:
  # url: https://github.com/dariober/cancer-variants-pipeline
  # sha256: '{{sha256}}'

build:
  number: 0
  skip: True # [not linux]

requirements:
  host:
  run:
    - python >=3.6
    - snakemake =5.4.0
    - fastqc =0.11.8
    - bwa =0.7.17
    - bbmap =38.22
    - igvtools =2.3.93
    - gatk4 =4.1.0.0
    - cnv_facets >=0.12.1
    - ensembl-vep =95.1 # Need to install cache files
    - samtools =1.9
    - bcftools =1.9
    - pyfaidx =0.5.5.2
    - pandas =0.24.0
    - pyyaml =3.13
    - colorama =0.4.1
    - libgfortran =3.0.0

test:
  commands:
    - medusa.py -h > /dev/null 2>&1 || [[ $? == 1 ]]

about:
  home: https://github.com/dariober/cancer-variants-pipeline
  license: MIT
  summary: Pipeline for detection of cancer somatic variants from high-throughput sequencing data
  license_family: MIT

extra:
  maintainers:
    - Dario Beraldi
